### ISSUE TITLE
<a name"x.x.x"> in release notes

### ISSUE THREAD

**Issue by palashmon** [palashmon/learn-commitizen#6]
Found `<a name"x.x.x">` in this repo release notes :disappointed:

**Comment by palashmon** [comment]
Found all the issues & PR related to it all open for long time:

## Issues
-  https://github.com/semantic-release/semantic-release/issues/363
-  https://github.com/semantic-release/semantic-release/issues/374
-  https://github.com/semantic-release/release-notes-generator/issues/4

## PR
- https://github.com/semantic-release/release-notes-generator/pull/3
- https://github.com/semantic-release/release-notes-generator/pull/5

**Comment by gr2m** [comment]
thanks for compiling this overview Palash, it is very helpful!

I’ll keep you all posted in this issue moving forward: https://github.com/semantic-release/semantic-release/issues/411 Thanks for your patience and if you could help triaging open issues / PRs and mention me in the ones you think are most urgent, I’d appreciate it <3

**Comment by palashmon** [comment]
Sure. I will keep reviewing all the open issues / PRs and let you know if I find something urgent.

Regards!

**Comment by palashmon** [comment]
@gr2m Hi Gregor,

This issue is fixed now, as you can also see in the [new release](https://github.com/palashmon/learn-commitizen/releases).

Thanks for it!
